### ISSUE TITLE
Logging in isn't working in main app

### ISSUE THREAD

**Issue by cfjedimaster** [whizjs/netlify-identity-demo-vue#1]
I logged in, and got a successful message, but when I dismiss the dialog, the UI says I'm not logged in. If I try to hit a protected page I'm asked to login.

Tested with latest Firefox.

**Comment by medmin** [comment]
Did you use Google / Github account to login ? If so, sorry for the confusion.

I just disabled the third party oauth login feature from the netlify dashboard.

If you need a demo for Google Oauth, please check:
https://github.com/whizjs/superjs

**Comment by cfjedimaster** [comment]
I probably did - so going to close.
